/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.quanly;


import com.nhsys.ui.ManHinhChinh;
import static com.nhsys.ui.ManHinhChinh.lblTieuDe;

/**
 *
 * @author Hai Tran
 */
public class QL_Menu extends javax.swing.JPanel {

    /**
     * Creates new form QL_MenuCN
     */
    public QL_Menu(ManHinhChinh frm) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDoanhThuCN = new javax.swing.JPanel();
        lblDoanhThuCN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpnNhanVienCN = new javax.swing.JPanel();
        lblNhanVienCN = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jpnThucDonCN = new javax.swing.JPanel();
        lblThucDonCN = new javax.swing.JLabel();
        jpnHangHoaCN = new javax.swing.JPanel();
        lblHangHoaCN = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jpnDoanhThuCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnDoanhThuCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDoanhThuCNMouseClicked(evt);
            }
        });

        lblDoanhThuCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDoanhThuCN.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThuCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuCN.setText("DOANH THU");
        lblDoanhThuCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnDoanhThuCNLayout = new javax.swing.GroupLayout(jpnDoanhThuCN);
        jpnDoanhThuCN.setLayout(jpnDoanhThuCNLayout);
        jpnDoanhThuCNLayout.setHorizontalGroup(
            jpnDoanhThuCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoanhThuCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        jpnDoanhThuCNLayout.setVerticalGroup(
            jpnDoanhThuCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoanhThuCN, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Documents\\Tai Lieu\\MonHoc-DuAn1\\Du-An-1\\QuanLyNhaHang\\logos\\logo.png")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(250, 250));
        jLabel9.setMinimumSize(new java.awt.Dimension(250, 250));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jpnNhanVienCN.setBackground(new java.awt.Color(204, 204, 204));

        lblNhanVienCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNhanVienCN.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVienCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVienCN.setText("NHÂN VIÊN");
        lblNhanVienCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnNhanVienCNLayout = new javax.swing.GroupLayout(jpnNhanVienCN);
        jpnNhanVienCN.setLayout(jpnNhanVienCNLayout);
        jpnNhanVienCNLayout.setHorizontalGroup(
            jpnNhanVienCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanVienCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnNhanVienCNLayout.setVerticalGroup(
            jpnNhanVienCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanVienCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jpnThucDonCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnThucDonCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnThucDonCNMouseClicked(evt);
            }
        });

        lblThucDonCN.setBackground(new java.awt.Color(204, 204, 204));
        lblThucDonCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblThucDonCN.setForeground(new java.awt.Color(255, 255, 255));
        lblThucDonCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThucDonCN.setText("THỰC ĐƠN");
        lblThucDonCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThucDonCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnThucDonCNLayout = new javax.swing.GroupLayout(jpnThucDonCN);
        jpnThucDonCN.setLayout(jpnThucDonCNLayout);
        jpnThucDonCNLayout.setHorizontalGroup(
            jpnThucDonCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThucDonCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        jpnThucDonCNLayout.setVerticalGroup(
            jpnThucDonCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThucDonCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jpnHangHoaCN.setBackground(new java.awt.Color(204, 204, 204));
        jpnHangHoaCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHangHoaCNMouseClicked(evt);
            }
        });

        lblHangHoaCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHangHoaCN.setForeground(new java.awt.Color(255, 255, 255));
        lblHangHoaCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHangHoaCN.setText("HÀNG HÓA");
        lblHangHoaCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHangHoaCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnHangHoaCNLayout = new javax.swing.GroupLayout(jpnHangHoaCN);
        jpnHangHoaCN.setLayout(jpnHangHoaCNLayout);
        jpnHangHoaCNLayout.setHorizontalGroup(
            jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblHangHoaCN, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        jpnHangHoaCNLayout.setVerticalGroup(
            jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jpnHangHoaCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblHangHoaCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnThucDonCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHangHoaCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnThucDonCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHangHoaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDoanhThuCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpnNhanVienCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnNhanVienCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDoanhThuCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblDoanhThuCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuCNMouseClicked
        // TODO add your handling code here:
        lblTieuDe.setText("DOANH THU THÁNG");

    }//GEN-LAST:event_lblDoanhThuCNMouseClicked

    private void jpnDoanhThuCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDoanhThuCNMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jpnDoanhThuCNMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseClicked

    private void lblNhanVienCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienCNMouseClicked
        // TODO add your handling code here:
        lblTieuDe.setText("DANH SÁCH NHÂN VIÊN");
    }//GEN-LAST:event_lblNhanVienCNMouseClicked

    private void lblThucDonCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThucDonCNMouseClicked
        lblTieuDe.setText("DANH SÁCH MÓN ĂN");
    }//GEN-LAST:event_lblThucDonCNMouseClicked

    private void jpnThucDonCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThucDonCNMouseClicked
        // TODO add your handling code here:
        //        new QLDanhSachChucNang().setVisible(true);
    }//GEN-LAST:event_jpnThucDonCNMouseClicked

    private void lblHangHoaCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHangHoaCNMouseClicked
        lblTieuDe.setText("DANH SÁCH HÀNG HÓA");
    }//GEN-LAST:event_lblHangHoaCNMouseClicked

    private void jpnHangHoaCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaCNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnHangHoaCNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JPanel jpnDoanhThuCN;
    public static javax.swing.JPanel jpnHangHoaCN;
    public static javax.swing.JPanel jpnNhanVienCN;
    public static javax.swing.JPanel jpnThucDonCN;
    public static javax.swing.JLabel lblDoanhThuCN;
    public static javax.swing.JLabel lblHangHoaCN;
    public static javax.swing.JLabel lblNhanVienCN;
    public static javax.swing.JLabel lblThucDonCN;
    // End of variables declaration//GEN-END:variables

//     public void fillmenuQL(){
//        menu.removeAll();
//        JPanel menuPanel = new NV_MenuMHC(fr);
//        menuPanel.setSize(220, 663);
//        menuPanel.repaint();
//        menuPanel.validate();
//        
//        menu.add(menuPanel);
//        menu.setPreferredSize(new Dimension(220, 663));
//        menu.repaint();
//        menu.validate();
//        
//        ChuyenMangHinhtroller  controller = new ChuyenMangHinhtroller(MHC);
//        controller.setView(jpnSoDoBanQL, lblSoDoBanQL);
//        
//        List<DanhMucBean> listItem =new ArrayList<>();
//        listItem.add(new DanhMucBean("SoDoBan", jpnSoDoBanQL, lblSoDoBanQL));
//        listItem.add(new DanhMucBean("KhoaSo", jpnDoanhThuCN, lblDoanhThuCN));
//        listItem.add(new DanhMucBean("ThanhVien", jpnChamCongCN, lblChamCongCN));      
//        controller.setEvent(listItem);
//    }
}
